# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/viz',
                'doc_host': 'https://bobprice0.github.io',
                'git_url': 'https://github.com/bobprice0/viz',
                'lib_path': 'viz'},
  'syms': {'viz.core': {'viz.core.foo': ('core.html#foo', 'viz/core.py')}}}
