# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/viz',
                'doc_host': 'https://bobprice0.github.io',
                'git_url': 'https://github.com/bobprice0/viz',
                'lib_path': 'viz'},
  'syms': { 'viz.core': { 'viz.core.ComplexShim': ('core.html#complexshim', 'viz/core.py'),
                          'viz.core.ComplexShim.__init__': ('core.html#complexshim.__init__', 'viz/core.py'),
                          'viz.core.abs_plot': ('core.html#abs_plot', 'viz/core.py'),
                          'viz.core.cplot3d': ('core.html#cplot3d', 'viz/core.py'),
                          'viz.core.default_color_function': ('core.html#default_color_function', 'viz/core.py'),
                          'viz.core.do_abs_plot': ('core.html#do_abs_plot', 'viz/core.py'),
                          'viz.core.get_shim': ('core.html#get_shim', 'viz/core.py'),
                          'viz.core.phase_plot': ('core.html#phase_plot', 'viz/core.py'),
                          'viz.core.phase_plot_array': ('core.html#phase_plot_array', 'viz/core.py')}}}
